# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PlYmngxrU3_7CJV9wcQGrpBGO6xJQhtV
"""

import serial
import time

# Define the serial port and baud rate.
# Ensure the 'COM#' corresponds to what was seen in the Windows Device Manager
ser = serial.Serial('COM7', 9600)

def servo_position():
    user_input = input("\n Type servo move Angle degree [Angle = 0 , 45 , 90 , 180] / quit : ")
    if user_input =='servo move 0 degree':
        print("Servo Move 0 Degree")
        time.sleep(0.1) 
        ser.write(b'U') 
        servo_position()
    elif user_input =='servo move 45 degree':
        print("Servo Move 45 Degree")
        time.sleep(0.1)
        ser.write(b'L')
        servo_position()
    elif user_input =='servo move 90 degree':
        print("Servo Move 90 Degree")
        time.sleep(0.1)
        ser.write(b'B')
        servo_position()
        
    elif user_input =='servo move 180 degree':
        print("Servo Move 180 Degree")
        time.sleep(0.1)
        ser.write(b'R')
        servo_position()
        
        
        
    elif user_input =="quit" or user_input == "q":
        print("Program Exiting")
        time.sleep(0.1)
        ser.write(b'R')
        ser.close()
    else:
        print("Invalid input. Type on / off / quit.")
        servo_position()

time.sleep(2) # wait for the serial connection to initialize

servo_position()